# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e19df3fc16825b6f0cd6ea2e930db632239e4d64631e94a9dc981ff0a2076a4e39eadd8e201f3064aa415768c8435af00ab052bbe92c69e362fc5f5d20ae9ab

test:
  secret_key_base: c73ea8c1645a5a0ac3ca9009d66950ee9255100f79c40c61f392bd7330df49e28e8dd8a3ac0d232c2815861f1b37b6a4c3149f8f024d205016df7ecd77c74823

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
